import Head from "next/head";
import Image from "next/image";
import {useSession, signIn, signOut} from "next-auth/react";
import PageLayout1 from "../src/layouts/PageLayout1";
import ContentTransition from "../src/layouts/ContentTransition";

export default function Home() {
    const {data: session} = useSession();
    if (session) {
        return (
            <>
                Signed in as {session.user?.email} <br />
                <button onClick={() => signOut()}>Sign out</button>
            </>
        );
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageLayout1>
                <ContentTransition>
                    <div className="mx-auto max-w-7xl px-4 sm:px-6 md:px-8">
                        <h1 className="text-2xl font-semibold text-gray-900 dark:text-gray-300">
                            Home
                        </h1>
                    </div>
                    <div className="mx-auto max-w-7xl px-4 sm:px-6 md:px-8">
                        {/* Replace with your content */}
                        <div className="py-4">
                            <div className="h-96 rounded-lg border-4 border-dashed border-gray-200 dark:border-black">
                                <div className="text-red-500">ds sds</div> dsdsd
                                <button onClick={() => signIn()}>
                                    Sign in
                                </button>
                            </div>
                        </div>
                        {/* /End replace */}
                    </div>
                </ContentTransition>
            </PageLayout1>
        </div>
    );
}
